name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_IP: ${{ secrets.EC2_IP }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        echo "$EC2_KEY" > ec2_key.pem
        chmod 600 ec2_key.pem 

    - name: SSH into EC2 and Pull Latest Changes
      run: |
        echo "Connecting to EC2 and pulling changes..."
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_IP << 'EOF'
          cd /home/ubuntu/login-apache2 || exit
          git pull origin main  
          rm -rf build 
          npm install  
          npm run build  
          sudo systemctl restart apache2  
        EOF
