name: Deploy a Docker image to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-login-nginx .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-login-nginx:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl start docker  # Ensure Docker is running
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-login-nginx:latest
            docker stop $(docker ps -q) || true  # Stop any running containers
            docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/react-login-nginx:latest
